modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="vestis"
version="${file.jarVersion}"
displayName="Malum: Vestis"
displayURL="https://www.curseforge.com/minecraft/mc-mods/malum-vestis"
#logoFile="examplemod.png"
credits="Gronglegrowth: implementation\nShesaRamblingRose: art" #optional
authors="Gronglegrowth, ShesaRamblingRose" #optional
description='''
An addon to Sammy;'s Malum which uses Vanity to add additional cosmetics to equipment.
'''
[[dependencies.vestis]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vestis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vestis]]
    modId="malum"
    mandatory=true
    side="BOTH"
    versionRange="[1.20.1,)"
[[dependencies.vestis]]
    modId="vanity"
    mandatory=true
    side="BOTH"
    versionRange="[1.0.0,)"